### PR TITLE
made header sticky

### PR DESCRIPTION
**Pull request by AlexVCS**
added the sticky class to the header working on #30

### CODE REVIEW

**Comment by AlexVCS** [comment]
I haven't used Astro before and I had a tough time getting the project to run locally. I do think I added the right Tailwind class and it should stick now like you wanted.

**Comment by takanome-dev** [comment]
Hey @AlexVCS, thanks for opening this pr. Really appreciate it :heart: 

> I had a tough time getting the project to run locally.

My bad, I didn't add a contributing guide and didn't indicate the places where the header needs to be fixed :sweat: Will do that later (and probably deploy the project)

You will need to add `top-0` to the header so that it will be fixed and `z-index` to avoid overlapping. See video below.

### Other places where header needs to be fixed
- `clients/src/layouts/dashboard-layout.astro`
- `clients/src/layouts/new-post-layout.astro`

https://github.com/takanome-dev/blog-with-astro-golang/assets/79809121/3f83d99f-b779-4228-85e7-08b1b8980961

**Comment by AlexVCS** [comment]
> Hey @AlexVCS, thanks for opening this pr. Really appreciate it ❤️
> 
> > I had a tough time getting the project to run locally.
> 
> My bad, I didn't add a contributing guide and didn't indicate the places where the header needs to be fixed 😓 Will do that later (and probably deploy the project)
> 
> You will need to add `top-0` to the header so that it will be fixed and `z-index` to avoid overlapping. See video below.
> 
> ### Other places where header needs to be fixed
> * `clients/src/layouts/dashboard-layout.astro`
> * `clients/src/layouts/new-post-layout.astro`
> 
>  sticky-header.mp4

Hey thanks, I think it should be fixed now!

**Review by takanome-dev — APPROVED** [review]
LGTM

**Comment by takanome-dev** [comment]
One more thing before merging this. Are you participating in Hacktoberfest?

**Comment by AlexVCS** [comment]
> One more thing before merging this. Are you participating in Hacktoberfest?

yes I am!

**Pull request merged**
